name: "Unbound"
description: " is a validating, recursive, and caching DNS resolver."
version: "1.9.0"
slug: " is a validating, recursive, and caching DNS resolver."
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
